# **第一阶段：构建阶段**
FROM golang:1.23.1 AS builder

WORKDIR /app

# 复制依赖文件并下载依赖
COPY go.mod go.sum ./
RUN go mod download

# 复制源代码并构建
COPY . .
RUN go build -ldflags "-w -s" -o bin/tinyscheduler-server scheduler/main.go

# **第二阶段：运行阶段**
FROM ubuntu:latest

# 安装必要的 CA 证书（如果需要）

# 复制编译后的二进制文件
COPY --from=builder /app/bin/tinyscheduler-server /usr/local/bin/tinyscheduler-server

# 运行 tinykv-server
ENTRYPOINT ["/usr/local/bin/tinyscheduler-server"]
